[package]
name = "gui"
version = "0.1.0"
authors = ["msyfls123 <m18771058712@live.com>"]
edition = "2018"

[dependencies]

[dependencies.gtk]
version = "0.6.0"
features = ["v3_16"]

[[bin]]
name = 'gtk'
path = 'src/main.rs'