[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["msyfls123 <m18771058712@live.com>"]
edition = "2018"

[dependencies]

[[bin]]
name = "2017-9"
path = "src/aoc2017/day9.rs"

[[bin]]
name = "2017-10"
path = "src/aoc2017/day10.rs"

[[bin]]
name = "2017-11"
path = "src/aoc2017/day11.rs"

[[bin]]
name = "2017-12"
path = "src/aoc2017/day12.rs"

[[bin]]
name = "2017-13"
path = "src/aoc2017/day13.rs"

[[bin]]
name = "2017-14"
path = "src/aoc2017/day14.rs"