name: Test

on: push

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Rust cache
        uses: Swatinem/rust-cache@v1

      - name: Run test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p advent_of_code
